// Файл настроек виджета. Создаётся FoxFire Hub автоматически при каждом
// изменении настроек — вручную не редактируй, правки будут перезаписаны.
window.__FOXFIRE_WIDGET_CONFIG__ = {
  "twitchChannel": "progdy_",
  "youtubeChannel": "",
  "youtubeApiKey": "",
  "youtubeVideoIdOverride": "",
  "direction": "Новые снизу",
  "fontFamily": "Системный (по умолчанию)",
  "fontFamilyCustom": "",
  "animationStyle": "Плавно (fade)",
  "scale": 100,
  "fontSize": 18,
  "messageSpacing": 6,
  "cornerRadius": 18,
  "maxMessages": 40,
  "bgOpacity": 65,
  "showPlatformIcons": true,
  "showBadges": true,
  "showTimestamps": false,
  "highlightModActions": true,
  "enableThirdPartyEmotes": true,
  "textColor": "#f2eaff",
  "accentColor": "#b967ff",
  "viewMode": "Авто (по контексту)",
  "enableBackground": true,
  "bgColor": "#120a1e",
  "bgBlur": 0,
  "letterSpacing": 0,
  "wordSpacing": 0,
  "textBold": false,
  "textItalic": false,
  "textUnderline": false,
  "textCase": "Обычный",
  "shadowColor": "rgba(0,0,0,0.6)",
  "shadowOffsetX": 0,
  "shadowOffsetY": 1,
  "shadowBlur": 2,
  "badgeColorBroadcaster": "#ffb703",
  "badgeColorModerator": "#22d3ee",
  "badgeColorVip": "#b967ff",
  "badgeColorSubscriber": "#ff4fa3",
  "badgeColorStaff": "#ef4444",
  "badgeColorPartner": "#22c55e",
  "youtubeMode": "Без ключа (через Hub)"
};
